# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/kakaoenterprise/PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'XWMP3ToWAV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :dynamic

  # Pods for XWMP3ToWAV
  pod 'SBCCodecForIOS', '0.0.1'
  pod 'ffmpeg-kit-ios-audio', '~> 6.0.LTS'

  target 'XWMP3ToWAVTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
