# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'CodeFragmentation' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for CodeFragmentation
  pod 'Masonry'
  pod 'SnapKit'
  pod 'JCore'
  pod 'JPush' 
#  pod 'NotificationBannerSwift', '~> 3.0.0'
end

target 'CodeFragmentationTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'CodeFragmentationUITests' do
    # Pods for testing
end


