# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

def uikit_pods
  pod 'Masonry', '~> 1.1.0'
  pod 'SnapKit', '~> 4.2.0'
end

def business_pods
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'RxSwiftExt', '~> 5'
end

def other_pods
  pod 'JCore', '~> 2.4.0'
  pod 'JPush', '~> 3.4.0'
end

target 'CodeFragmentation' do
  uikit_pods
  business_pods
  other_pods
end

target 'CodeFragmentationTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'CodeFragmentationUITests' do
    # Pods for testing
end

# Script for setting swift version of PromiseKit to 4.2, since it for some reason sets the version to 5, even though it does not support it.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RxSwift'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
    target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
  end
end


